services:
  - type: web
    name: user-service
    env: docker
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d2j4d5ili9vc73euvmbg-a.oregon-postgres.render.com:5432/agrosense_db
      - key: SPRING_DATASOURCE_USERNAME
        value: agrosense_db_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: rCocTXPKLkBNmN1T0zZlvJT0z6V3ujCg
